2024-10-28 00:06:07,747 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\gnusa\UrbanUniversity\Modules\Modele_12\tests_12_4.py", line 81, in test_run
    obj_runner = Runner(Object_to_be_tested)
                        ^^^^^^^^^^^^^^^^^^^
NameError: name 'Object_to_be_tested' is not defined
2024-10-28 00:06:07,762 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\gnusa\UrbanUniversity\Modules\Modele_12\tests_12_4.py", line 70, in test_walk
    obj_runner = Runner('Object to be tested', speed=-5)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnusa\UrbanUniversity\Modules\Modele_12\tests_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
